### ISSUE TITLE
[🐛 BUG]: Exceptions not printed to the browser in the debug mode

### ISSUE THREAD

**Issue by speller** [roadrunner-server/roadrunner#1781] opened 2023-11-15 03:30 UTC
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

When I use the `debug` mode for the HTTP pool and the app fails to startup, I see a blank screen and no debug info. I can only check for errors in the RR log.

I expect the default app's exception screen to be displayed. It was working as expected in v2.12.2 with the Reload plugin. After upgrading to the recent version and replacing `reload` with `debug`, I can not see the default app's exception screens, only the blank screen.

### Version (rr --version)

2023.3.4

### How to reproduce the issue?

- Setup debug mode
- Issue a Symfony startup exception (errors in the configuration for example).
- Make a request.

### Relevant log output

```shell
[15-Nov-2023 12:25:53 Asia/Tokyo] 2023-11-15T12:25:53+09:00 [critical] Uncaught Exception: You cannot dump a container with parameters that contain references to other services (reference to service "Aws\Credentials\InstanceProfileProvider" found in "/0/arguments/0/credentials").

2023-11-15T03:25:53+0000    ERROR   http            execute {"start": "2023-11-15T03:25:53+0000", "elapsed": "212.973631ms", "error": "goridge_frame_receive: validation failed on the message sent to STDOUT, see: https://roadrunner.dev/docs/known-issues-stdout-crc/current/en, invalid message: Symfony\\Component\\DependencyInjection\\Exception\\InvalidArgumentException {#4722\n  #message: \"You cannot dump a container with parameters that contain references to other services (reference to service \"Aws\\Credentials\\InstanceProfileProvider\" found in \"/0/arguments/0/credentials\").\"\n  #code: 0\n  #file: \"./vendor/symfony/dependency-injection/Dumper/PhpDumper.php\"\n  #line: 1721\n  trace: {\n    ./vendor/symfony/dependency-injection/Dumper/PhpDumper.php:1721 { …}\n    ./vendor/symfony/dependency-injection/Dumper/PhpDumper.php:1713 { …}\n    ./vendor/symfony/dependency-injection/Dumper/PhpDumper.php:1713 { …}\n    ./vendor/symfony/dependency-injection/Dumper/PhpDumper.php:1713 { …}\n    ./vendor/symfony/dependency-injection/Dumper/PhpDumper.php:1592 { …}\n    ./vendor/symfony/dependency-injection/Dumper/PhpDumper.php:238 { …}\n    ./vendor/symfony/http-kernel/Kernel.php:697 { …}\n    ./vendor/symfony/http-kernel/Kernel.php:516 { …}\n    ./vendor/symfony/http-kernel/Kernel.php:759 { …}\n    ./vendor/symfony/http-kernel/Kernel.php:126 { …}\n    ./vendor/baldinof/roadrunner-bundle/src/Runtime/Runner.php:24 { …}\n    ./vendor/autoload_runtime.php:29 { …}\n    ./index.php:5 {\n      › \n      › require_once __DIR__ . '/vendor/autoload_runtime.php';\n      › \n      arguments: {\n        \"/app/vendor/autoload_runtime.php\"\n      }\n    }\n  }\n}\n"}
2023-11-15 12:25:53 2023-11-15T03:25:53+0000    INFO    http            http log        {"status": 200, "method": "GET", "URI": "/favicon.ico", "remote_address": "172.18.0.1:53770", "read_bytes": 0, "write_bytes": 0, "start": "2023-11-15T03:25:53+0000", "elapsed": "213.085245ms"}
```

**Comment by rustatian** [comment] 2023-11-15 10:50
Hey @speller :wave: 
This is not a bug actually :smile: 
This was done on purpose to hide the error output in any mode. But, I've discussed this case with our PHP team and we decided, that it would be better to show the error in this mode. It will be fixed this Thursday in the `2023.3.5` bugfix release.

**Closed as completed** 2023-11-15 11:23 UTC
Labels: bug, C-enhancement, B-missing feature, P-HTTP

**Comment by speller** [comment] 2023-11-16 04:43
@rustatian thank you for the clarification.
At the same time, I would prefer to have an explicit option on whether to show or hide the application exception screen. Is it possible?

**Comment by rustatian** [comment] 2023-11-16 07:21
@speller You already have this option, it is called `debug`.

EDIT: I'm not sure that we need an additional option for that.

**Comment by speller** [comment] 2023-11-21 02:56
@rustatian I found that RR returns HTTP status code 200 when an exception happens and it outputs the exception details. I would expect code 500, because the server didn't fulfill the request and returns an error.

**Comment by rustatian** [comment] 2023-11-21 09:15
@speller I'm not quite sure what do you mean under - 'it outputs the exception detail' because in the `debug` mode, RR should show the exception.
As for the `200` code, I'm not sure that this is related to RR: https://github.com/roadrunner-server/http/blob/master/tests/http_plugin3_test.go#L115
I have a test for that case and check the `http` status code to be 500 on exceptions.
