### ISSUE TITLE
[🐛 BUG]: Env variables values from global env is not used in server.env

### ISSUE THREAD

**Issue by tony-sol** [roadrunner-server/roadrunner#1034] opened 2022-03-03 15:56 UTC
### No duplicates 🥲.

- [X] I have searched for a similar issue in our bug tracker and didn't find any solutions.

### What happened?

System env vars are not used in config file server.env section.

Config example:
```
version: '2.7'

server:
    command: "php /var/www/app/public/index.php"
    env:
        - APP_RUNTIME: "Baldinof\\RoadRunnerBundle\\Runtime\\Runtime"
           REDIS_DSN: ${REDIS_DSN}
# other stuff
```
Env is definitely exists:

![Снимок экрана 2022-03-03 в 18 53 27](https://user-images.githubusercontent.com/33671815/156601078-2c52569e-7feb-4e94-933b-279fd98b4807.png)

but after run server, i've checked $_SERVER and got this:

![Снимок экрана 2022-03-03 в 18 51 46](https://user-images.githubusercontent.com/33671815/156600828-153ad4b7-4ee5-421c-a9de-d5baa42100e4.png)

Is this a real bug?

### Version

2.8.2

### Relevant log output

```shell
2022-03-03T18:38:24.892+0300    INFO    server          {"message":"An error occured: Unsupported DSN: \"${REDIS_DSN}\".","context":{"throwable":{"class":"Symfony\\Component\\Cache\\Exception\\InvalidArgumentException","message":"Unsupported DSN: \"${REDIS_DSN}\".","code":0,"file":"/var/www/app/vendor/symfony/cache/Adapter/AbstractAdapter.php:141"}},"level":400,"level_name":"ERROR","channel":"app","datetime":"2022-03-03T18:38:24.872590+03:00","extra":{"cm_x_trace_id":"3de0c6c0197a52062a22215f2e28e258","cm_environment":"dev","cm_type":"ERROR","cm_time":"2022-03-03T18:38:24+03:00","cm_service":"php-blank","cm_version":"0.0.1","cm_x_pub":false}}
```

**Comment by rustatian** [comment] 2022-03-03 16:13
Hey, @Tony-Sol. The config should be as follows:

```yaml
version: '2.7'

server:
    command: "php /var/www/app/public/index.php"
    env:
        - APP_RUNTIME: "Baldinof\\RoadRunnerBundle\\Runtime\\Runtime"
        - REDIS_DSN: ${REDIS_DSN}
# other stuff
```
But, to use the `${}` notation, you should set that by yourself via: https://github.com/spiral/roadrunner-docs/blob/master/php/environment.md#using-environment-variables-in-the-configuration

**Comment by tony-sol** [comment] 2022-03-03 16:21
Thanks for answer

It's aclually a bad formatting, but envs are not substituted neither with
```
    env:
        - APP_RUNTIME: "Baldinof\\RoadRunnerBundle\\Runtime\\Runtime"
          REDIS_DSN: ${REDIS_DSN}
```
nor
```
    env:
        - APP_RUNTIME: "Baldinof\\RoadRunnerBundle\\Runtime\\Runtime"
        - REDIS_DSN: ${REDIS_DSN}
```
syntax.

Also, i had suggestion that it's similar to [this issue](https://github.com/roadrunner-server/roadrunner/issues/142) or that env usage also requires `-o` flag?

**Comment by rustatian** [comment] 2022-03-03 16:24
You are welcome. But RRv2 doesn't support such notation like: `${}`. If you use configuration with that notation, you should have a look at this approach: https://github.com/spiral/roadrunner-docs/blob/master/php/environment.md#using-environment-variables-in-the-configuration

**Comment by rustatian** [comment] 2022-03-03 16:26
No, env variables don't require the `-o` flag. However, you may use it, but this is not required.

**Comment by tony-sol** [comment] 2022-03-03 16:59
Maybe, i'm wrong, but it seems to me kind a bad practice 😞 
For example:

i have 2 separate configs: `dev.yml` and `prod.yml` and docker development environment, included via git submodule.

in `prod.yml` i have ansible-value encrypted REDIS_DNS, DATABASE_URL, etc. - those variables also defined in docker .env for local development

So it looks more clear for others to have identical keys dev and prod configs, without duplicate their actual values or removing their keys from `dev.yml`.

**Comment by rustatian** [comment] 2022-03-03 17:48
That's not a bad practice 😃 That's how to set the env variables. If you wanted to have that as a feature request, please, describe your case, create a new ticket (because that's not a bug) and we will plan it for the next sprints 😃

**Comment by rustatian** [comment] 2022-03-04 07:49
@Tony-Sol I'll close this ticket (since that's not a bug). Feel free to create a feature request if you need to have that as a new feature. Thanks.

**Closed as completed by rustatian** 2022-03-04 07:49 UTC
Labels: bug, F-need-verification
